FINAL_PIPELINE_COLS = [
    "age_group_id",
    "sex_id",
    "location_id",
    "year_start",
    "year_end",
    "bundle_id",
    "estimate_id",
    "diagnosis_id",
    "source_type_id",
    "nid",
    "representative_id",
    "mean",
    "lower",
    "upper",
    "sample_size",
    "run_id",
]

COL_DATA_TYPES = {
    "age": float,
    "age_start": float,
    "age_end": float,
    "age_group_id": int,
    "year": int,
    "year_start": int,
    "year_end": int,
    "year_id": int,
    "sex_id": int,
    "location_id": int,
    "location_id_gbd": str,
    "location_id_cnty": str,
    "bene_id": str,
    "dob": str,
    "dod": str,
    "month_id": int,
    "days": float,
    "eligibility_reason": str,
    "entitlement": int,
    "part_c": bool,
    "five_percent_sample": bool,
    "eh_five_percent_sample": bool,
    "restricted_benefit": str,
    "managed_care": int,
    "bundle_id": int,
    "estimate_id": int,
    "diagnosis_id": int,
    "source_type_id": int,
    "nid": int,
    "representative_id": int,
    "run_id": int,
    "mean": float,
    "lower": float,
    "upper": float,
    "sample_size": float,
    "cause_code": str,
    "diagnosis_id": int,
    "claim_id": str,
    "code_system_id": int,
}