//  Purpose: Use proportions file (generated by: get_proportions.ado) to redistribute HIV garbage


// Define program
cap program drop apply_proportions
program define apply_proportions, nclass
	version 13
	
	quietly {
	if c(os) == "Windows" BREAK NO LONGER WORKS ON WINDOWS
	gen year_range = ""
	foreach year of numlist 1980(5)2015 {
		local year_end = `year'+4
		replace year_range = "`year'_`year_end'" if year >= `year' & year <= `year_end'
	}
	** Use 1985-1989 for reference year, so deaths there are non-zero values there
	replace year_range = "1985_1989" if year < 1985
	gen p_reg = .
	foreach region_used of local regions_used {
		replace p_reg = `region_used' if region == `region_used'
	}
	replace p_reg = 1 if p_reg == .
	** Bring in proportions, apply to deaths, assign new causes and acauses based on targets
	joinby p_reg sex year_range list cause acause using "$prefix/WORK/03_cod/01_database/02_programs/hiv_correction/rdp_proportions/data/hiv_rdp_props.dta", unmatched(master)
	foreach x of numlist 3 7/22 91 93 94 {
		replace deaths`x' = deaths`x'*prop`x' if _m == 3
	}
	replace cause = "acause_" + target if _m == 3
	replace acause = target if _m == 3
	replace cause = "ZZZ" if target == "ZZZ" & _m == 3
	replace acause = "_gc" if target == "ZZZ" & _m == 3
	drop deaths1 deaths2
	egen deaths1 = rowtotal(deaths*)
	egen deaths2 = rowtotal(deaths91 deaths93 deaths94)
	drop p_reg year_range prop* target _m
	noisily di "PROPORTIONS APPLIED"
	}
end
