# ---HEADER--------------------------------------------------------------------------------------------------
# Project: Non-fatal CKD Remission Calculation
# Purpose: Calculate 'remission' ratios for CKD stages from incidence and prevalence estimates generated by 
# DisMod. This script pulls in the incidence and prevalence draws and calcualtes a ratio of incidence to 
#------------------------------------------------------------------------------------------------------------

# ---SETTINGS------------------------------------------------------------------------------------------------
# Versioning 
output_version <-1 

# Stages 
stage_3_4<-T
stage_4_5<-T
dialysis_transplant<-T
#-------------------------------------------------------------------------------------------------------------

# ---CONFIG--------------------------------------------------------------------------------------------------

#System settings
slots<- 5
mem <- slots*2 
shell <- paste0('FILEPATH/new_r_shell.sh')
delete_remission<-paste0('FILEPATH/delete_remission_ratios.R')
script_01 <- paste0('FILEPATH/01_ratios.R')
script_02 <- paste0('FILEPATH/02_append_and_save.R')
project <- '-P USERNAME' 
sge_output_dir <- '-o FILEPATH -e FILEPATH '

# load packages 
require(data.table)

# source functions
source(paste0('FILEPATH/get_location_metadata.R'))
#-------------------------------------------------------------------------------------------------------------


# ---SETTINGS-------------------------------------------------------------------------------------------------
#Create list of most detailed locations to parallelize over
location_dt<- get_location_metadata(location_set_id = 9,gbd_round_id = 4)
location_dt<-location_dt[most_detailed==1,list(location_id,location_name,location_type)] 
locations<-location_dt[,location_id]

#specify acause 
acause<-'ckd' 
#-------------------------------------------------------------------------------------------------------------

# --- STAGE 5 TO STAGE 4 RATIOS-------------------------------------------------------------------------------
if (stage_4_5==T){
  num_me_id<- 2022
  num_bundle_id<- 186
  denom_me_id<-2019
  denom_bundle_id<- 183

  #specify where to save your output 
  out_dir<-paste0("FILEPATH/",output_version)
  dir.create(out_dir,recursive = TRUE)
  
  job_name<- paste0('-N delete_remission_stg4')
  sys_sub<- paste0('qsub ', project, sge_output_dir, job_name, ' -pe multi_slot ',slots, ' -l mem_free=', mem, 'G')
  system(paste(sys_sub, shell, delete_remission, denom_bundle_id, acause))
  print(paste(sys_sub, shell, delete_remission, denom_bundle_id, acause))
  
  for (loc in locations) {
    #create qsub
    location_type<-location_dt[location_id==loc,location_type]
    job_name<- paste0('-N stg4_',loc)
    sys_sub<- paste0('qsub -cwd ', project, sge_output_dir, job_name, ' -pe multi_slot ',slots, ' -l mem_free=', mem, 'G')
    system(paste(sys_sub, shell, script_01, loc, num_me_id, num_bundle_id,denom_me_id,denom_bundle_id,out_dir,location_type))
    print(paste(sys_sub, shell, script_01, loc, num_me_id, num_bundle_id,denom_me_id,denom_bundle_id,out_dir,location_type))
  }
  job_name<- paste0('-N save_stg4')
  sys_sub<- paste0('qsub -cwd ', project, sge_output_dir, job_name, ' -pe multi_slot ',slots, ' -l mem_free=', mem, 'G')
  system(paste(sys_sub, shell, script_02, out_dir))
  print(paste(sys_sub, shell, script_02, out_dir))
}
#-------------------------------------------------------------------------------------------------------------

  
# --- STAGE 4 TO STAGE 3 RATIOS-------------------------------------------------------------------------------
if(stage_3_4==T){
  num_me_id<- 2019
  num_bundle_id<- 183
  denom_me_id<-2018
  denom_bundle_id<- 182
  
  #specify where to save your output 
  out_dir<-paste0("FILEPATH",output_version)
  dir.create(out_dir,recursive = TRUE)
  
  job_name<- paste0('-N delete_remission_stg3')
  sys_sub<- paste0('qsub ', project, sge_output_dir, job_name, ' -pe multi_slot ',slots, ' -l mem_free=', mem, 'G')
  system(paste(sys_sub, shell, delete_remission, denom_me_id,denom_bundle_id))
  print(paste(sys_sub, shell, delete_remission, denom_me_id,denom_bundle_id))
  
  for (loc in locations) {
    #create qsub
    location_type<-location_dt[location_id==loc,location_type]
    job_name<- paste0('-N stg3_',loc)
    sys_sub<- paste0('qsub -cwd ', project, sge_output_dir, job_name, ' -pe multi_slot ',slots, ' -l mem_free=', mem, 'G')
    system(paste(sys_sub, shell, script_01, loc, num_me_id, num_bundle_id,denom_me_id,denom_bundle_id,out_dir,location_type))
    print(paste(sys_sub, shell, script_01, loc, num_me_id, num_bundle_id,denom_me_id,denom_bundle_id,out_dir,location_type))
  }
  job_name<- paste0('-N save_stg3')
  sys_sub<- paste0('qsub -cwd ', project, sge_output_dir, job_name, ' -pe multi_slot ',slots, ' -l mem_free=', mem, 'G')
  system(paste(sys_sub, shell, script_02, out_dir))
  print(paste(sys_sub, shell, script_02, out_dir))
}
#-------------------------------------------------------------------------------------------------------------

# --- DIALYSIS/TRANSPLANT RATIO-------------------------------------------------------------------------------
if(dialysis_transplant==T){
  num_me_id<- 2020
  num_bundle_id<- 184
  denom_me_id<-2021
  denom_bundle_id<- 185
  
  #specify where to save your output 
  out_dir<-paste0("FILEPATH",output_version)
  dir.create(out_dir,recursive = TRUE)
  
  job_name<- paste0('-N delete_remission_dial')
  sys_sub<- paste0('qsub ', project, sge_output_dir, job_name, ' -pe multi_slot ',slots, ' -l mem_free=', mem, 'G')
  system(paste(sys_sub, shell, delete_remission, denom_me_id,denom_bundle_id))
  print(paste(sys_sub, shell, delete_remission, denom_me_id,denom_bundle_id))
  
  for (loc in locations) {
    #create qsub
    location_type<-location_dt[location_id==loc,location_type]
    job_name<- paste0('-N dial_tx_',loc)
    sys_sub<- paste0('qsub -cwd ', project, sge_output_dir, job_name, ' -pe multi_slot ',slots, ' -l mem_free=', mem, 'G')
    system(paste(sys_sub, shell, script_01, loc, num_me_id, num_bundle_id,denom_me_id,denom_bundle_id,out_dir,location_type))
    print(paste(sys_sub, shell, script_01, loc, num_me_id, num_bundle_id,denom_me_id,denom_bundle_id,out_dir,location_type))
  }
  job_name<- paste0('-N save_dial_tx')
  sys_sub<- paste0('qsub -cwd ', project, sge_output_dir, job_name, ' -pe multi_slot ',slots, ' -l mem_free=', mem, 'G')
  system(paste(sys_sub, shell, script_02, out_dir))
  print(paste(sys_sub, shell, script_02, out_dir))
}
#-------------------------------------------------------------------------------------------------------------
