# ---HEADER--------------------------------------------------------------------------------------------------
# Project: Non-fatal CKD Remission Calculation
# Purpose: Calculate 'remission' ratios for CKD stages from incidence and prevalence estimates generated by 
# DisMod. This script pulls in the incidence and prevalence draws and calcualtes a ratio of incidence to 
# prevalence 
#------------------------------------------------------------------------------------------------------------

# ---CONFIG--------------------------------------------------------------------------------------------------

# source functions
source(paste0("FILEPATH/function_lib.R"))
source_shared_functions(c("get_draws","get_ids"))
#-------------------------------------------------------------------------------------------------------------

#Pass arguments from qsub  
  args<-commandArgs(trailingOnly = TRUE)
  loc<-as.numeric(args[1])
  num_me_id <- as.numeric(args[2])
  num_bundle_id<-as.numeric(args[3])
  denom_me_id<-as.numeric(args[4])
  denom_bundle_id<-as.numeric(args[5])
  out_dir<-args[6]
  location_type<-args[7]

#Source age map
  age_dt<-get_age_map(5)
  ages<-age_dt[,age_group_id]

#specify years and sexes that we want
  years<-c(seq(1990,2010,5),2017)
  sexes<-c(1,2)

#pull in incidence dismod results for the numerator
  print("getting numerator draws")
  num <-get_draws(gbd_id_field='modelable_entity_id', 
                  gbd_id= num_me_id, 
                  source='epi', 
                  measure_ids=6, 
                  location_ids=loc,
                  year_ids=years,
                  sex_ids=sexes, 
                  age_group_ids=ages,
                  status='best',
                  gbd_round_id=4)

#Pull in prevalence dismod results for the denominator 
  print("getting denominator draws")
  denom <-get_draws(gbd_id_field='modelable_entity_id', 
                    gbd_id= denom_me_id, 
                    source='epi', 
                    measure_ids=5, 
                    location_ids=loc,
                    year_ids=years,
                    sex_ids=sexes, 
                    age_group_ids=ages,
                    status='best',
                    gbd_round_id=4)

#Calculate ratio
  #set id variable to merge by 
  idvars<-c('location_id','sex_id','age_group_id','year_id')
  #drop modelable_entity_id, model_version_id, and measure_id
  num<-num[,c('modelable_entity_id','model_version_id','measure_id'):=NULL]
  denom<-denom[,c('modelable_entity_id','model_version_id','measure_id'):=NULL]
  #rename "draws_#" cols 
  draw_cols<-paste0("draw_",0:999)
  num_cols<-paste0("numerator_",0:999)
  denom_cols <- paste0("denominator_", 0:999)
  setnames(num, draw_cols, num_cols)
  setnames(denom, draw_cols, denom_cols)
  #merge num and denom
  ratios <- merge(num, denom, by=idvars,with=FALSE)
  #divide num draws by denom draws 
  ratios[, (draw_cols) := lapply(1:1000, function(draw) get(num_cols[draw]) / get(denom_cols[draw]))]
  
  #drop num and denom draws
  ratios<-ratios[,c(num_cols,denom_cols):=NULL]

#calculate mean of draws
  ratios[,mean:=apply(.SD,1,mean),.SDcols=draw_cols]
#calculate quantiles for draws 
  ratios[,upper:=apply(.SD,1,quantile,c(0.975)),by=idvars,.SDcols=draw_cols]
  ratios[,lower:=apply(.SD,1,quantile,c(0.025)),by=idvars,.SDcols=draw_cols]

#drop draw cols
  ratios[,(draw_cols):=NULL]

#merge on age_start and age_end
  ratios<-merge(ratios,age_dt[,.(age_start,age_end,age_group_id)],by='age_group_id', all.x=TRUE)

#add on rows needed for epi uploader
  ratios[,year_end:=year_id]
  ratios[,year_start:=year_id]
  blank_cols<-c("underlying_nid","page_num", "table_num","smaller_site_unit", "site_memo","standard_error", 
                "note_modeler", "note_SR","sampling_type", "response_rate", "case_name", "case_definition", 
                "case_diagnostics","seq", "seq_parent", "underlying_field_citation_value","input_type",
                "effective_sample_size","cases","recall_type_value", "sample_size","design_effect")
  ratios[,(blank_cols):=NA]
  issue_cols<-c("sex_issue","year_issue","age_issue","measure_issue","measure_adjustment","is_outlier")
  ratios[,(issue_cols):=0]
  ratios[sex_id==1,sex:='Male']
  ratios[sex_id==2,sex:='Female']
  ratios[,measure:='remission']
  ratios[,source_type:="Mixed or estimation"]
  ratios[,urbanicity_type:='Unknown']
  if (location_type=='admin0'){
    ratios[,representative_name:='Nationally representative only']
  } else {
    ratios[,representative_name:='Representative for subnational location only']
  }
  ratios[,unit_type:='Person']
  ratios[,unit_value_as_published:=1]
  ratios[,recall_type:='Point']
  ratios[,uncertainty_type:='Confidence interval']
  ratios[,uncertainty_type_value:=95]
  ratios[,bundle_id:=denom_bundle_id]
  if (denom_me_id==2018){
    ratios[,field_citation_value:=('Institute for Health Metrics and Evaluation (IHME). IHME DisMod Stage III Chronic Kidney Disease Remission Estimates.')]
    ratios[,nid:=251359]
  } else if (denom_me_id==2019){
    ratios[,field_citation_value:=('Institute for Health Metrics and Evaluation (IHME). IHME DisMod Stage IV Chronic Kidney Disease Remission Estimates.')]
    ratios[,nid:=251358]
  } else if (denom_me_id==2021){
    ratios[,field_citation_value:=('Institute for Health Metrics and Evaluation (IHME). IHME End-stage Renal Disease DisMod Transplant Incidence Estimates.')]
    ratios[,nid:=294381]
  }
  ratios[,extractor:=Sys.info()[['user']]]
  
#drop extra cols 
  ratios[,c("sex_id","age_group_id","year_id"):=NULL]

#output csv 
  write.csv(ratios,paste0('FILEPATH',loc,'.csv'),na='')

