# ---HEADER--------------------------------------------------------------------------------------------------
# Author: 
# Date: 12/23/2016
# Project: Non-fatal CKD Remission Calculation
# Purpose: Calculate 'remission' ratios for CKD stages from incidence and prevalence estimates generated by 
# DisMod. Pulls in the incidence and prevalence draws and calcualtes a ratio of incidence to 
# prevalence 
#------------------------------------------------------------------------------------------------------------

# ---CONFIG--------------------------------------------------------------------------------------------------
# set runtime configuration 
if (Sys.info()['sysname'] == 'Linux') {
  j_root <- '/home/j/' 
  h_root <- '/homes/USERNAME/'
} else { 
  j_root <- 'J:/'
  h_root <- 'H:/'
}

# load packages 
require(data.table)

# source functions
source(paste0("FILEPATH",'get_draws.R'))
source(paste0("FILEPATH",'get_ids.R'))
#-------------------------------------------------------------------------------------------------------------

#Pass arguments from qsub  
  args<-commandArgs(trailingOnly = TRUE)
  loc<-as.numeric(args[1])
  num_me_id <- as.numeric(args[2])
  num_bundle_id<-as.numeric(args[3])
  denom_me_id<-as.numeric(args[4])
  denom_bundle_id<-as.numeric(args[5])
  out_dir<-args[6]
  location_type<-args[7]

#Source age map
  age_dt<-fread("FILEPATH")
  ages<-age_dt[age_group_id%in%c(2:20,30:32,235),age_group_id]

#specify years and sexes that we want
  years<-c(seq(1990,2010,5),2016)
  sexes<-c(1,2)

#pull in incidence dismod results for the numerator
  num <-get_draws(gbd_id_field='modelable_entity_id', 
                  gbd_id= num_me_id, 
                  source='epi', 
                  measure_ids=6, 
                  location_ids=loc,
                  year_ids=years,
                  sex_ids=sexes, 
                  age_group_ids=ages,
                  status='best')

#Pull in prevalence dismod results for the denominator 
  denom <-get_draws(gbd_id_field='modelable_entity_id', 
                    gbd_id= denom_me_id, 
                    source='epi', 
                    measure_ids=5, 
                    location_ids=loc,
                    year_ids=years,
                    sex_ids=sexes, 
                    age_group_ids=ages,
                    status='best')

#Calculate ratio
  #set id variable to merge by 
  idvars<-c('location_id','sex_id','age_group_id','year_id')
  #drop modelable_entity_id, model_version_id, and measure_id
  num<-num[,c('modelable_entity_id','model_version_id','measure_id'):=NULL]
  denom<-denom[,c('modelable_entity_id','model_version_id','measure_id'):=NULL]
  #rename "draws_#" cols 
  draw_cols<-paste0("draw_",0:999)
  num_cols<-paste0("numerator_",0:999)
  denom_cols <- paste0("denominator_", 0:999)
  setnames(num, draw_cols, num_cols)
  setnames(denom, draw_cols, denom_cols)
  #merge num and denom
  ratios <- merge(num, denom, by=idvars,with=FALSE)
  #divide num draws by denom draws 
  ratios[, (draw_cols) := lapply(1:1000, function(draw) get(num_cols[draw]) / get(denom_cols[draw]))]
  
  #drop num and denom draws
  ratios<-ratios[,c(num_cols,denom_cols):=NULL]

#calculate mean of draws
  ratios[,mean:=apply(.SD,1,mean),.SDcols=draw_cols]
#calculate quantiles for draws 
  ratios[,upper:=apply(.SD,1,quantile,c(0.975)),by=idvars,.SDcols=draw_cols]
  ratios[,lower:=apply(.SD,1,quantile,c(0.025)),by=idvars,.SDcols=draw_cols]

#drop draw cols
  ratios[,(draw_cols):=NULL]

#merge on age_start and age_end
  ratios<-merge(ratios,age_dt,by='age_group_id', all.x=TRUE)

#output csv 
  write.csv(ratios,paste0(out_dir,'/',denom_me_id,'_',loc,'.csv'),na='')

