# ---HEADER--------------------------------------------------------------------------------------------------
# Author: 
# Date: 12/23/2016
# Project: Non-fatal CKD Remission Calculation
# Purpose: Calculate 'remission' ratios for CKD stages from incidence and prevalence estimates generated by 
# DisMod. This script pulls in the incidence and prevalence draws and calcualtes a ratio of incidence to 
# prevalence 
#------------------------------------------------------------------------------------------------------------

# ---CONFIG--------------------------------------------------------------------------------------------------
# set runtime configuration 
if (Sys.info()['sysname'] == 'Linux') {
  j_root <- '/home/j/' 
  h_root <- '/homes/USERNAME/'
} else { 
  j_root <- 'J:/'
  h_root <- 'H:/'
}

# load packages 
require(data.table)
require(magrittr)
require(openxlsx)

# source functions
source(paste0("FILEPATH",'get_location_metadata.R'))

# set objects 
args<-commandArgs(trailingOnly = TRUE)
out_dir<-args[1]
#-------------------------------------------------------------------------------------------------------------

# ---BODY-----------------------------------------------------------------------------------------------------
#Create list of locations that was parallelized over 
location_dt<- get_location_metadata(location_set_id = 9) 
location_dt<-location_dt[most_detailed==1,list(location_id,location_name,location_type)] 
locations<-location_dt[,location_id]

# check number of files in ouput directory 
file_count<-list.files(out_dir,pattern = "\\.csv$")%>%length()

# wait until number of files in output directory is equal to expected number of output files 
while (file_count<length(locations)){
  Sys.sleep(60)
  file_count<-list.files(out_dir,pattern = "\\.csv$")%>%length()
} 

# once all files are present, append them and output .csv
if (file_count==length(locations)){
  file_list<-list.files(out_dir,pattern = "\\.csv$")
  remission<-rbindlist(lapply(paste0(out_dir,'/',file_list),fread))
  #merge on location_name from the location_dt 
  extraction<-merge(remission,location_dt[,-c('location_type'),with=F],by='location_id',all.x=TRUE)
  write.xlsx(extraction[,-c('V1'),with=F],paste0(out_dir,'/extraction.csv'),row.names=FALSE,sheetName="extraction")
}
#-------------------------------------------------------------------------------------------------------------
