default:
  col_year: year_start
  col_time: time_start
  col_data:
    - deaths
    - population
    - age_name
    - sex
    - location_id
    - deaths_covid
  time_unit: week
  time_start:
    year: 2010
    detailed: 1
  time_end_0:
    year: 2020
    detailed: 8
  time_end_1:
    year: 2022
    detailed: 53
  age_groups:
    - 0 to 125
    - 0 to 5
    - 5 to 10
    - 10 to 15
    - 15 to 20
    - 20 to 25
    - 25 to 30
    - 30 to 35
    - 35 to 40
    - 40 to 45
    - 45 to 50
    - 50 to 55
    - 55 to 60
    - 60 to 65
    - 65 to 70
    - 70 to 75
    - 75 to 80
    - 80 to 85
    - 85 to 90
    - 90 to 125
  sex_groups:
    - all
    - male
    - female
  knots_per_year: 0.333
  tail_size: 104
  smooth_order: 1
