#' Subtract HIV cause-specific mx values from 45q15 and 5q0
#'
#' Subtract HIV cause-specific mx, bounded by HIV proportion proportion values, from 45q15 and 5q0 to
#'    generate HIV-free 45q15 and 5q0 values
#'
#' @param qx_draws data.table with variables: ihme_loc_id, year, sex, sim, entry_45q15, entry_5q0
#'                 With-HIV results from the 5q0 and 45q15 processes (location/age/sex/year/draw-specific)
#' @param hiv_draws data.table with variables: ihme_loc_id, year, sex, adult_hiv_cdr, child_hiv_cdr.
#'     Post-rescaling HIV CDR based on various scaling values. Now mean values rather than draw-specific.
#' @param hiv_prop_range data.table with variables: ihme_loc_id, sex, upper_adult, upper_child. Generated by
#'     Spectrum, perhaps the upper 97.5 percentile bound on HIV deaths/envelope proportion
#' @param hiv_ctry_groups data.table with variables: ihme_loc_id, sex, group (character). Used to generate a
#'     floor for HIV-free values in high-HIV countries that risk having a false floor of HIV.
#'
#' @return data.table with variables: ihme_loc_id, year, sex, sim, calc_45q15, calc_5q0
#' @export
#'
#' @import data.table 
#' @import assertable

subtract_hiv_mx <- function(qx_draws, hiv_draws, hiv_prop_range, hiv_ctry_groups) {

	## Merge all input datasets together
		orig_rows <- nrow(qx_draws)

		qx_draws <- merge(qx_draws, hiv_draws, by=c("ihme_loc_id", "year", "sex"))
		qx_draws <- merge(qx_draws, hiv_prop_range, by=c("ihme_loc_id", "sex"))
		qx_draws <- merge(qx_draws, hiv_ctry_groups, by = c("ihme_loc_id"), all.x=T)

		if(orig_rows != nrow(qx_draws)) stop("Qx draws did not merge with HIV prop range appropriately -- check that HIV prop ranges exist for ihme_loc_id (or fix in input data)")

	## Cap HIV CDR to the upper limit imposed by hiv_prop_range (which must be max prop of HIV deaths out of envelope)
		qx_draws[adult_hiv_cdr / qx_to_mx(entry_45q15, 45) > upper_adult, adult_hiv_cdr := qx_to_mx(entry_45q15, 45) * upper_adult]
		qx_draws[child_hiv_cdr / qx_to_mx(entry_5q0, 5) > upper_child, child_hiv_cdr := qx_to_mx(entry_5q0, 5) * upper_child]

	## Subtract HIV CDR (in mx space) from 45q15 in mx space, then convert back to qx space
		qx_draws[, calc_45q15 := mx_to_qx(qx_to_mx(entry_45q15, 45) - adult_hiv_cdr, 45)]
		qx_draws[, calc_5q0 := mx_to_qx(qx_to_mx(entry_5q0, 5) - child_hiv_cdr, 5)]

	## Set minimum bounds on adult and child qx values for HIV-free in endemic countries (where HIV-free may get pushed down)
		qx_draws[calc_45q15 < .13 & sex == "male" & group %in% c("1A"), calc_45q15 := .13]
		qx_draws[calc_45q15 < .08 & sex == "female" & group %in% c("1A"), calc_45q15 := .08]
		qx_draws[calc_5q0 < .005 & group %in% c("1A"), calc_5q0 := .005]

	## Make sure that HIV-free 45q15 and 5q0 is not higher than entry values if they exist (if triggered by minimum bounds above)
	## Here, just make HIV-free just smaller than with-HIV if there are differences
		qx_draws[entry_45q15 < calc_45q15, calc_45q15 := entry_45q15 - .0000001]
		qx_draws[entry_5q0 < calc_5q0, calc_5q0 := entry_5q0 - .0000001]
		
	assert_values(qx_draws, c("calc_5q0", "calc_45q15"), "not_na", quiet=T)
	assert_values(qx_draws, c("calc_5q0", "calc_45q15"), "gte", 0, quiet=T)

	return(qx_draws)
}
