QUEUE: str = 'all.q'

CALCULATE_HALE_CORES: int = 2
CALCULATE_HALE_MEMORY: str = '7G'
CALCULATE_HALE_RUNTIME: int = 600

UPLOAD_CORES: int = 2
UPLOAD_MEMORY: str = '5G'
UPLOAD_RUNTIME: int = 600

CLEAN_CORES: int = 1
CLEAN_MEMORY: str = '500M'
CLEAN_RUNTIME: int = 300
