####################################################################################################
## Description: Predict full lifetables from GBD abridged lifetables using regression fits from HMD
##              full lifetables. Makes key assumption that ax is 0.5 for all age groups besides the
##              first and last age groups.
####################################################################################################
rm(list=ls())
options(digits=22)
# Import
username <- Sys.getenv("USER")

library(data.table)
library(readr)
library(rhdf5)
library(assertable)
library(slackr)
library(argparse)

library(ltcore, lib = "FILEPATH/r-pkg")
library(mortdb, lib = "FILEPATH/r-pkg")
library(mortcore, lib = "FILEPATH/r-pkg")


# Get settings ------------------------------------------------------------

# Parse arguments
parser <- ArgumentParser()
parser$add_argument('--no_shock_death_number_estimate_version', type="integer", required=TRUE,
                    help='The run id of no shock death number estimate')
parser$add_argument('--loc', type="integer", required=TRUE,
                    help='The location_id to run')
parser$add_argument('--shock_aggregator_version', type="integer", required=TRUE,
                    help='The run id of the shock aggregator version')
parser$add_argument('--mlt_life_table_estimate_version', type="integer", required=TRUE,
                    help='The run id of the mlt life table estimate version')
parser$add_argument('--hiv_run', type="character", required=TRUE,
                    help='HIV run')
parser$add_argument('--gbd_year', type="integer", required=TRUE,
                    help="GBD year")
parser$add_argument('--enable_assertions_flag', type="character", required=TRUE,
                    help="Enable assertions flag")



args <- parser$parse_args()
VERSION_NO_SHOCK_DEATH_NUMBER <- args$no_shock_death_number_estimate_version
LOCATION_ID <- args$loc
GBD_YEAR <- args$gbd_year
VERSION_SHOCK_AGGREGATOR <- args$shock_aggregator_version
VERSION_MLT_LT_NUMBER <- args$mlt_life_table_estimate_version
HIV_RUN <- args$hiv_run
ENABLE_ASSERTIONS <- as.logical(args$enable_assertions_flag)

MAX_AGE <- 110
INPUT_YEARS <- c(1950:GBD_YEAR)

code_dir <- "FILEPATH"
source(paste0(code_dir, "/helper_funcs.R"))
source(paste0(code_dir, "/validation_funcs.R"))
source(paste0(code_dir, "/import_hiv_draws.R"))
source(paste0(code_dir, "/reconcile_hiv.R"))

OUTPUT_DIR <- "FILEPATH + VERSION_NO_SHOCK_DEATH_NUMBER"
# Generated by 5qx_1qx_coeffs_scatters.R
REGRESSION_DIR <- "FILEPATH"

MLT_DIR <- "FILEPATH + VERSION_MLT_LT_NUMBER"
NO_HIV_LT_DIR <- paste0(MLT_DIR, "/lt_hiv_free/scaled")
WITH_HIV_LT_DIR <- paste0(MLT_DIR, "/lt_with_hiv/scaled")
WITH_HIV_ENV_DIR <- paste0(MLT_DIR, "/env_with_hiv/scaled")

# Load cached datasets
age_groups <- fread(file = paste0(OUTPUT_DIR, "/inputs/age_groups.csv"))
population <- fread(paste0(OUTPUT_DIR, "/inputs/population.csv"))[location_id == LOCATION_ID,]
population[, c("lower", "upper", "ihme_loc_id") := NULL]
population_sy <- fread(paste0(OUTPUT_DIR, "/inputs/population_sy.csv"), drop = c("lower", "upper", "ihme_loc_id"))[location_id == LOCATION_ID,]
age_groups_sy <- fread(paste0(OUTPUT_DIR, "/inputs/age_groups_sy.csv"))[, .(age_group_id, age = age_group_years_start)]
population_sy <- merge(population_sy, age_groups_sy, by = "age_group_id", all.x = T)
population_sy[age_group_id == 235, age := 95] # Single-year populations only go up to 95+, whereas SY age groups go through 110
population_sy[, age_group_id := NULL]
single_abridged_age_map <- fread(paste0(OUTPUT_DIR, "/inputs/single_abridged_age_map.csv"))

loc_map <- fread(paste0(OUTPUT_DIR, "/inputs/location_hierarchy.csv"))
HIV_GROUP <- loc_map[location_id == LOCATION_ID, group]
if(is.na(HIV_GROUP)) stop("HIV group not defined")

id_vars <- c("location_id", "year_id", "sex_id", "draw")


####################################################################################################
# Define Functions ---------------------------------------------------------------
mx_to_ax <- function (m, t)
{
  result <- t + 1/m - t/(1-exp(-t*m))
  return(result)
}

format_mx_ax_for_full_gen_lt <- function(dataset, age_groups) {
  dataset = dataset[sex_id != 3]
  dataset = merge(dataset, age_groups, by = "age_group_id")
  dataset[, qx := mx_ax_to_qx(mx, ax, age_length)]
  dataset[age == MAX_AGE, qx := 1]

    if (nrow(dataset[qx > 1]) > 0) {
      print(dataset[qx > 1])
      stop("Found rows where qx is greater than 1 after conversion.")
    }

  dataset[, px := 1 - qx]
  dataset[, age_group_id := NULL]

  return(dataset)
}

# create summary qx and ax, with associated upper and lower bounds
summarize_lt <- function(lifetable, full_lt) {
  lt_ids <- c("location_id", "year_id", "sex_id", "draw", "age")
  mean_lt_ids <- lt_ids[lt_ids != "draw"]
  measure_vars <- c("ax", "mx")

  ## For full lifetables, also generate nLx
  if(full_lt == T) {
    replacement_lt_params <- c("nLx", "Tx", "lx", "ex", "qx")

    measure_vars <- c(measure_vars, replacement_lt_params)
    lifetable <- copy(lifetable)
    setkeyv(lifetable, lt_ids)
    lifetable[, age_length := 1]
    qx_to_lx(lifetable)
    lx_to_dx(lifetable)
    gen_nLx(lifetable)
    gen_Tx(lifetable, id_vars = lt_ids)
    gen_ex(lifetable)
    lifetable[, mx := qx_ax_to_mx(qx, ax, 1)]
  }

  life_table_summary <- melt(lifetable,
                             value.name = "value",
                             id.vars = lt_ids,
                             measure.vars = measure_vars,
                             variable.name = "life_table_parameter_name",
                             variable.factor = F)

  life_table_summary <- life_table_summary[, list(lower = quantile(value, probs = c(.025)), upper = quantile(value, probs = c(.975)), mean = mean(value)),
                                           by = c(mean_lt_ids, "life_table_parameter_name")]

  ## Calculate mean nLx, lx, Tx based off of the mean LT rather than mean of draw-level nLx values
  if(full_lt == T) {
    mean_mx <- life_table_summary[life_table_parameter_name == "mx"]
    setnames(mean_mx, "mean", "mx")
    mean_ax <- life_table_summary[life_table_parameter_name == "ax"]
    setnames(mean_ax, "mean", "ax")

    mean_lt <- merge(mean_mx, mean_ax, by = mean_lt_ids)
    mean_lt[, age_length := 1]
    mean_lt[, qx := mx_ax_to_qx(mx, ax, 1)]
    mean_lt[age == 110, qx := 1]
    mean_lt[age == 110, mx := qx_ax_to_mx(qx, ax, 1)]

    setkeyv(mean_lt, mean_lt_ids)
    qx_to_lx(mean_lt)
    lx_to_dx(mean_lt)
    gen_nLx(mean_lt)
    gen_Tx(mean_lt, id_vars = mean_lt_ids)
    gen_ex(mean_lt)

    mean_lt <- melt(mean_lt,
                    value.name = "replacement_mean",
                    id.vars = mean_lt_ids,
                    measure.vars = replacement_lt_params,
                    variable.name = "life_table_parameter_name",
                    variable.factor = F)

    life_table_summary <- merge(life_table_summary, mean_lt, by = c(mean_lt_ids, "life_table_parameter_name"), all.x = T)
    life_table_summary[life_table_parameter_name %in% replacement_lt_params, mean := replacement_mean]
    life_table_summary[, replacement_mean := NULL]
  }

  return(life_table_summary)
}

gen_abridged_mx_ax_qx <- function(draw_level_full_lt, id_vars) {
  abridged_lt <- copy(draw_level_full_lt)
  setkeyv(abridged_lt, c(id_vars, "age"))
  qx_to_lx(abridged_lt, terminal_age = MAX_AGE)
  lx_to_dx(abridged_lt, terminal_age = MAX_AGE)
  abridged_lt[, lx := NULL]

  abridged_lt <- gen_abridged_lt(abridged_lt, id_vars, assert_qx = ENABLE_ASSERTIONS)

  abridged_lt <- merge(abridged_lt, age_groups[, list(age, age_length)], by = "age")
  abridged_lt[age == MAX_AGE, qx := 1]

  if (nrow(abridged_lt[qx > .9999 & age != MAX_AGE]) > 0) {
    warning("Found rows where qx is greater than .9999 after conversion. Capping at .9999")
    abridged_lt[qx > .9999 & age != MAX_AGE, qx := .9999]
  }

  abridged_lt[, mx := qx_ax_to_mx(qx, ax, age_length)]
  return(abridged_lt)
}


####################################################################################################
# Load shock deaths and convert to full single-year results with life table ages
shock_numbers <- tryCatch({
  fread("FILEPATH + VERSION_SHOCK_AGGREGATOR + LOCATION_ID")
}, warning = function(w) {
  warning("fread failed to read the shock aggregator file - trying read_csv from readr")
  read_csv("FILEPATH + VERSION_SHOCK_AGGREGATOR + LOCATION_ID")
}, error = function(e) {
  warning("fread failed to read the shock aggregator file - trying read_csv from readr")
  read_csv("FILEPATH + VERSION_SHOCK_AGGREGATOR + LOCATION_ID")
})

shock_numbers <- shock_numbers[cause_id == 294,] ## in shocks file, cause_id 294 is all-cause shocks

validate_shock_aggregator(shock_numbers)

shock_numbers <- shock_numbers[, cause_id := NULL]

shock_numbers <- melt(shock_numbers, value.name = "deaths",
                      id.vars = c("location_id", "sex_id", "age_group_id", "year_id"),
                      measure.vars = grep("draw", names(shock_numbers), value = T),
                      variable.name = "draw",
                      variable.factor = F)

shock_numbers[, draw := as.integer(substr(draw, 6, nchar(draw)))]

shock_numbers_28 <- aggregate_deaths(dataset = shock_numbers, target_age_group_id = 28, child_age_group_ids = c(2, 3, 4), id_vars = c("location_id", "year_id", "sex_id", "draw"))
shock_numbers <- rbindlist(list(shock_numbers, shock_numbers_28), use.names = T)
rm(shock_numbers_28)

shock_numbers_to_save <- shock_numbers[age_group_id != 28]
shock_numbers_to_save[, location_id := LOCATION_ID]
fwrite(shock_numbers_to_save, paste0(OUTPUT_DIR, "/shock_numbers/finalizer_shock_deaths_", LOCATION_ID, ".csv"))

rm(shock_numbers_to_save)

shock_rates <- calculate_rates(shock_numbers, population)

shock_rates <- add_lt_ages(shock_rates)
setnames(shock_rates, "death_rate", "shock_rate")

shock_rates <- merge(shock_rates, age_groups[, list(age_group_id, age)], by = "age_group_id")
setnames(shock_rates, "age", "abridged_age")
shock_rates[, age_group_id := NULL]

single_year_shock_rates <- expand_ages(shock_rates, single_abridged_age_map)
assert_values(single_year_shock_rates, names(single_year_shock_rates), test = "not_na", quiet = T)

rm("shock_numbers", "shock_rates")


####################################################################################################
# Load HIV deaths and convert to full single-year results with life table ages
hiv_deaths <- import_hiv_draws(HIV_RUN, LOCATION_ID, HIV_GROUP, GBD_YEAR,
                               hiv_ages = c(2:20, 28, 30:32, 235),
                               loc_map = loc_map,
                               pop_dt = population)

## Load with-hiv envelope results to cap HIV at 90% of PNN results
hiv_env_files <- paste0(WITH_HIV_ENV_DIR, "/with_hiv_env_", INPUT_YEARS, ".h5")
import_pnn_whiv_env <- function(x, by_val) {
  data <- setDT(load_hdf(x, by_val))
  data <- data[age_group_id %in% c(4) & sex_id != 3]
  return(data)
}

pnn_env_draw <- setDT(rbindlist(lapply(hiv_env_files, import_pnn_whiv_env, by_val = LOCATION_ID)))
setnames(pnn_env_draw, c("sim", "deaths"), c("draw", "with_hiv_deaths"))
pnn_env_draw <- merge(pnn_env_draw, population, by = c(id_vars[id_vars != "draw"], "age_group_id"))
pnn_env_draw[, with_hiv_mx_pnn := with_hiv_deaths / mean_population]

hiv_deaths <- hiv_deaths[!age_group_id %in% c(2:4)]
setnames(hiv_deaths, "mx_spec_hiv", "death_rate")

hiv_deaths <- add_lt_ages(hiv_deaths)
setnames(hiv_deaths, "death_rate", "mx_spec_hiv")

hiv_deaths <- merge(hiv_deaths, age_groups[, list(age_group_id, age)], by = "age_group_id")
setnames(hiv_deaths, "age", "abridged_age")
hiv_deaths[, age_group_id := NULL]

single_year_hiv_rates <- expand_ages(hiv_deaths, single_abridged_age_map)
assert_values(single_year_hiv_rates, c("mx_spec_hiv"), test = "not_na", quiet = T)

rm("hiv_deaths")


####################################################################################################
# Read in lifetable data and prep for interpolation, HIV reconciliation, and shock addition

## Load no-hiv mx and ax MLT file
no_hiv_mx_ax_files <- paste0(NO_HIV_LT_DIR, "/hiv_free_lt_", INPUT_YEARS, ".h5")
no_hiv_lt_draw <- setDT(rbindlist(lapply(no_hiv_mx_ax_files, load_hdf, by_val = LOCATION_ID)))
setnames(no_hiv_lt_draw, c("sim", "year"), c("draw", "year_id"))
no_hiv_lt_draw <- no_hiv_lt_draw[sex != "both"]
no_hiv_lt_draw[sex == "male", sex_id := 1]
no_hiv_lt_draw[sex == "female", sex_id := 2]
no_hiv_lt_draw[, sex := NULL]
no_hiv_lt_draw <- merge(no_hiv_lt_draw, age_groups[, .(age, age_group_id, age_length)], by = "age")
no_hiv_lt_draw[age>=5&age<110,ax := mx_to_ax(mx, age_length)]
no_hiv_lt_draw[, age := NULL]
no_hiv_lt_draw[, age_length := NULL]
validate_mx_ax(no_hiv_lt_draw)

no_hiv_lt_draw <- format_mx_ax_for_full_gen_lt(no_hiv_lt_draw, age_groups)

## Load with-hiv mx and ax reckoning file
hiv_mx_ax_files <- paste0(WITH_HIV_LT_DIR, "/with_hiv_lt_", INPUT_YEARS, ".h5")
hiv_lt_draw <- setDT(rbindlist(lapply(hiv_mx_ax_files, load_hdf, by_val = LOCATION_ID)))
setnames(hiv_lt_draw, c("sim", "year"), c("draw", "year_id"))
hiv_lt_draw <- hiv_lt_draw[sex != "both"]
hiv_lt_draw[sex == "male", sex_id := 1]
hiv_lt_draw[sex == "female", sex_id := 2]
hiv_lt_draw[, sex := NULL]
hiv_lt_draw <- merge(hiv_lt_draw, age_groups[, .(age, age_group_id, age_length)], by = "age")
hiv_lt_draw[age>=5&age<110,ax := mx_to_ax(mx, age_length)]
hiv_lt_draw[, age := NULL]
hiv_lt_draw[, age_length := NULL]
validate_mx_ax(hiv_lt_draw)

hiv_lt_draw <- format_mx_ax_for_full_gen_lt(hiv_lt_draw, age_groups)


# Load in regression and run full lifetable for no-hiv and with-hiv -------
fits <- fread(paste0(REGRESSION_DIR, "log_fit_coefficients.csv"))

no_hiv_full_lt_draw <- gen_full_lt(no_hiv_lt_draw, fits, id_vars, terminal_age = MAX_AGE, assert_qx = ENABLE_ASSERTIONS)
no_hiv_full_lt_draw[age>=5&age<MAX_AGE, no_hiv_mx := qx_to_mx(qx, 1)]
no_hiv_full_lt_draw[age<5|age==MAX_AGE, no_hiv_mx := qx_ax_to_mx(qx, ax, 1)]

hiv_full_lt_draw <- gen_full_lt(hiv_lt_draw, fits, id_vars, terminal_age = MAX_AGE, assert_qx = ENABLE_ASSERTIONS)
hiv_full_lt_draw[age>=5&age<MAX_AGE, with_hiv_mx := qx_to_mx(qx, 1)]
hiv_full_lt_draw[age<5|age==MAX_AGE, with_hiv_mx := qx_ax_to_mx(qx, ax, 1)]

hiv_full_lt_draw <- merge(no_hiv_full_lt_draw[, .SD, .SDcols = c(id_vars, "age", "no_hiv_mx")],
                          hiv_full_lt_draw[, .SD, .SDcols = c(id_vars, "age", "ax", "with_hiv_mx")],
                          by = c(id_vars, "age"))

hiv_full_lt_draw[with_hiv_mx < no_hiv_mx, with_hiv_mx := no_hiv_mx] # In case the full LT interpolation causes single-year variation across the two mx values

# Run HIV reconciliation process to reconcile life table and HIV results
hiv_full_lt_draw <- reconcile_hiv(hiv_full_lt_draw, single_year_hiv_rates, pnn_env_draw, population_sy, HIV_GROUP, c(id_vars, "age"))
hiv_adjust_input <- hiv_full_lt_draw[["hiv_adjust_input"]]
hiv_full_lt_draw <- hiv_full_lt_draw[["full_lt"]]

no_hiv_full_lt_draw <- hiv_full_lt_draw[, .SD, .SDcols = c(id_vars, "age", "ax", "no_hiv_mx")]
setnames(no_hiv_full_lt_draw, "no_hiv_mx", "mx")

hiv_full_lt_draw <- hiv_full_lt_draw[, .SD, .SDcols = c(id_vars, "age", "ax", "with_hiv_mx")]
setnames(hiv_full_lt_draw, "with_hiv_mx", "mx")

# Add shocks to death results
shock_full_lt_draw <- merge(hiv_full_lt_draw, single_year_shock_rates, by = c(id_vars, "age"), all.x = T)

# add shocks by multiplying mx with shock rate
shock_full_lt_draw[, mx := mx + shock_rate]
shock_full_lt_draw <- shock_full_lt_draw[, .SD, .SDcols = c(id_vars, "age", "ax", "mx")]


####################################################################################################
# Standardize and validate life table values
# recalculate qx using with-shock mx
no_hiv_full_lt_draw[age<5|age==MAX_AGE, qx := mx_ax_to_qx(mx, ax, 1)]
no_hiv_full_lt_draw[age>=5&age<MAX_AGE, qx := mx_to_qx(mx, 1)]
no_hiv_full_lt_draw[age == MAX_AGE, qx := 1]

hiv_full_lt_draw[age<5|age==MAX_AGE, qx := mx_ax_to_qx(mx, ax, 1)]
hiv_full_lt_draw[age>=5&age<MAX_AGE, qx := mx_to_qx(mx, 1)]
hiv_full_lt_draw[age == MAX_AGE, qx := 1]

shock_full_lt_draw[age<5|age==MAX_AGE, qx := mx_ax_to_qx(mx, ax, 1)]
shock_full_lt_draw[age>=5&age<MAX_AGE, qx := mx_to_qx(mx, 1)]
shock_full_lt_draw[age == MAX_AGE, qx := 1]

cap_full_lt_draws <- function(dt, assert_qx = ENABLE_ASSERTIONS) {

  if (assert_qx & (nrow(dt[qx > 1]) > 0)) {
    print(dt[qx > 1])
    stop("Found rows in draw-level life table where qx is greater than 1 after conversion.")
  }

}

cap_full_lt_draws(no_hiv_full_lt_draw)
cap_full_lt_draws(hiv_full_lt_draw)
cap_full_lt_draws(shock_full_lt_draw)

rm(single_year_shock_rates)

# validate mx for single-year lifetables ----------------------------------

diagnostics <- validate_draw_lt_mx(no_hiv_full_lt_draw, hiv_full_lt_draw, shock_full_lt_draw)

if (!is.null(diagnostics$with_hiv_vs_no_hiv)) {
  diagnostic_file <- paste0(OUTPUT_DIR, "/logs/full_with_hiv_mx_vs_no_hiv/with_hiv_mx_vs_no_hiv_", LOCATION_ID, ".csv")
  warning(paste0("Found rows where single-year with-hiv mx is less than no-hiv mx, saving affected rows here: ", diagnostic_file))
  fwrite(diagnostics$with_hiv_vs_no_hiv, diagnostic_file)
}

if (!is.null(diagnostics$shock_vs_with_hiv)) {
  diagnostic_file <- paste0(OUTPUT_DIR, "/logs/full_shock_mx_vs_with_hiv/shock_mx_vs_with_hiv_", LOCATION_ID, ".csv")
  warning(paste0("Found rows where single-year with-shock mx is less than with-hiv mx, saving affected rows here: ", diagnostic_file))
  fwrite(diagnostics$shock_vs_with_hiv, diagnostic_file)
}


# Calculate abridged life tables ------------------------------------------

# no-hiv life tables
no_hiv_abridged_lt_draw <- gen_abridged_mx_ax_qx(no_hiv_full_lt_draw, id_vars)
validate_abridged_qx(no_hiv_abridged_lt_draw, paste0(OUTPUT_DIR, "/logs/abridged_no_hiv_qx_1_5"))

# no-shock with-hiv life tables
hiv_abridged_lt_draw <- gen_abridged_mx_ax_qx(hiv_full_lt_draw, id_vars)
validate_abridged_qx(hiv_abridged_lt_draw, paste0(OUTPUT_DIR, "/logs/abridged_with_hiv_qx_1_5"))

# with-shock with-hiv life tables
shock_abridged_lt_draw <- gen_abridged_mx_ax_qx(shock_full_lt_draw, id_vars)
validate_abridged_qx(shock_abridged_lt_draw, paste0(OUTPUT_DIR, "/logs/abridged_shock_qx_1_5"))


# validate mx for abridged lifetables ------------------------------------------

diagnostics <- validate_draw_lt_mx(no_hiv_abridged_lt_draw, hiv_abridged_lt_draw, shock_abridged_lt_draw)

if (!is.null(diagnostics$with_hiv_vs_no_hiv)) {
  diagnostic_file <- paste0(OUTPUT_DIR, "/logs/abridged_with_hiv_mx_vs_no_hiv/with_hiv_mx_vs_no_hiv_", LOCATION_ID, ".csv")
  warning(paste0("Found rows where abridged with-hiv mx is less than no-hiv mx, saving affected rows here: ", diagnostic_file))
  fwrite(diagnostics$with_hiv_vs_no_hiv, diagnostic_file)
}

if (!is.null(diagnostics$shock_vs_with_hiv)) {
  diagnostic_file <- paste0(OUTPUT_DIR, "/logs/abridged_shock_mx_vs_with_hiv/shock_mx_vs_with_hiv_", LOCATION_ID, ".csv")
  warning(paste0("Found rows where abridged with-shock mx is less than with-hiv mx, saving affected rows here: ", diagnostic_file))
  fwrite(diagnostics$shock_vs_with_hiv, diagnostic_file)
}

rm(diagnostics)


# Calculate summary lifetables -------------------------------------------------

# summary lts
# no-hiv summary life tables
no_hiv_full_lt_summary <- summarize_lt(no_hiv_full_lt_draw, full_lt = T)

# no-shock with-hiv summary life tables
hiv_full_lt_summary <- summarize_lt(hiv_full_lt_draw, full_lt = T)

# with-shock with-hiv summary life tables
shock_full_lt_summary <- summarize_lt(shock_full_lt_draw, full_lt = T)

# Abridged lts
# no-hiv summary life tables
no_hiv_abridged_lt_summary <- summarize_lt(no_hiv_abridged_lt_draw, full_lt = F)
no_hiv_abridged_lt_summary <- merge(no_hiv_abridged_lt_summary, age_groups[, list(age, age_group_id)], by = "age")

# no-shock with-hiv summary life tables
hiv_abridged_lt_summary <- summarize_lt(hiv_abridged_lt_draw, full_lt = F)
hiv_abridged_lt_summary <- merge(hiv_abridged_lt_summary, age_groups[, list(age, age_group_id)], by = "age")

# with-shock with-hiv summary life tables
shock_abridged_lt_summary <- summarize_lt(shock_abridged_lt_draw, full_lt = F)
shock_abridged_lt_summary <- merge(shock_abridged_lt_summary, age_groups[, list(age, age_group_id)], by = "age")


# Prep and check draws and summary lifetables -----------------------------

if (ENABLE_ASSERTIONS) {
  print("Validating full LT draws")
  validate_full_lifetable_draw(no_hiv_full_lt_draw)
  validate_full_lifetable_draw(hiv_full_lt_draw)
  validate_full_lifetable_draw(shock_full_lt_draw)

  print("Validating abridged LT draws")
  validate_abridged_lifetable_draw(no_hiv_abridged_lt_draw, no_hiv_lt_draw, paste0(OUTPUT_DIR, "/logs/ax_compare"))
  validate_abridged_lifetable_draw(hiv_abridged_lt_draw, hiv_lt_draw, paste0(OUTPUT_DIR, "/logs/ax_compare"))
  validate_abridged_lifetable_draw(shock_abridged_lt_draw)

  print("Validating full LT summary")
  validate_full_lifetable_summary(no_hiv_full_lt_summary)
  validate_full_lifetable_summary(hiv_full_lt_summary)
  validate_full_lifetable_summary(shock_full_lt_summary)
}


# Save lifetables ---------------------------------------------------------

# HIV adjustment inputs
fwrite(hiv_adjust_input, paste0(OUTPUT_DIR, "/hiv_adjust/hiv_adjust_", LOCATION_ID, ".csv"))

# no hiv
fwrite(no_hiv_full_lt_draw,  paste0(OUTPUT_DIR, "/full_lt/no_hiv/lt_full_draw_", LOCATION_ID, ".csv"))
fwrite(no_hiv_abridged_lt_draw,  paste0(OUTPUT_DIR, "/abridged_lt/no_hiv/lt_abridged_draw_", LOCATION_ID, ".csv"))
fwrite(no_hiv_full_lt_summary,  paste0(OUTPUT_DIR, "/full_lt/no_hiv/summary_full_", LOCATION_ID, ".csv"))
fwrite(no_hiv_abridged_lt_summary,  paste0(OUTPUT_DIR, "/abridged_lt/no_hiv/summary_abridged_", LOCATION_ID, ".csv"))

# with hiv
fwrite(hiv_full_lt_draw,  paste0(OUTPUT_DIR, "/full_lt/with_hiv/lt_full_draw_", LOCATION_ID, ".csv"))
fwrite(hiv_abridged_lt_draw,  paste0(OUTPUT_DIR, "/abridged_lt/with_hiv/lt_abridged_draw_", LOCATION_ID, ".csv"))
fwrite(hiv_full_lt_summary,  paste0(OUTPUT_DIR, "/full_lt/with_hiv/summary_full_", LOCATION_ID, ".csv"))
fwrite(hiv_abridged_lt_summary,  paste0(OUTPUT_DIR, "/abridged_lt/with_hiv/summary_abridged_", LOCATION_ID, ".csv"))

# with-shock
fwrite(shock_full_lt_draw,  paste0(OUTPUT_DIR, "/full_lt/with_shock/lt_full_draw_", LOCATION_ID, ".csv"))
fwrite(shock_abridged_lt_draw,  paste0(OUTPUT_DIR, "/abridged_lt/with_shock/lt_abridged_draw_", LOCATION_ID, ".csv"))
fwrite(shock_full_lt_summary,  paste0(OUTPUT_DIR, "/full_lt/with_shock/summary_full_", LOCATION_ID, ".csv"))
fwrite(shock_abridged_lt_summary,  paste0(OUTPUT_DIR, "/abridged_lt/with_shock/summary_abridged_", LOCATION_ID, ".csv"))
